
### Create lobby
POST http://localhost:8090/api/lobbies
content-type: application/json

{
  "gameID": "8fae4d9a-8dfb-4d64-95c3-6c6b234e57a1",
  "lobbyAdminId": "95592601-d766-4715-a205-fbd13323ccc3"
}

### join lobby
PATCH http://localhost:8090/api/lobbies/joinLobby
content-type: application/json

{
  "lobbyId": "5ee57dfe-c7fb-4023-8a15-0bb6a2e8cc32",
  "guestId": "8fae4d9a-8dfb-4d64-95c3-6c6b234e57a1"
}

